### ISSUE TITLE
 Sending and receiving at the same time

### ISSUE THREAD

**Issue by lhk** [regnets/Pewduino#2]
In my setup I use two arduinos. One for sending, the other for receiving.
This means that I can detect hits even while firing.
The problem is: Communication between the two arduinos is not implemented yet. I would like to use a serial connection. But then the connection between arduino and PC is dropped = no debugging = programming nightmare.

I'm seriously doubting wether I can program this without debugging.
So I'm considering a one arduino solution.

At this point I encountered the problems with IRlib, searched online, found your project and read up on the code. You use only one arduino, right ?
Does that work for you ?

66 samples per signal, let's say an average of 1000 per mark and space. I believe that this number is a multiple of the carrier frequency. So 38kHz times 66000. That's about two seconds per signal. That surely can't be right.

Did you ever experience "invulnerability" while shooting ?
Did you experiment with burst fire modes (they should make it even worse) ?

**Comment by regnets** [comment]
I am using a "one arduino" solution, however you will be invulnerable while you are sending data (the irlib turns of the receiver part while sending).

However the whole transmission is not two secondes long. You can calculate how long your signal is.

For this calculation you don't need the frequency as this is just the frequency band and not the real ups and downs (or high and lows) in your signal.

You could use the irlib debug method to see how (timely) long your signal is.

In my case i think i got 900µs for every mark and space with a header of 6750µs (just as example).

So i need 66 raw samples where 63 (remember the first and last are undefined long) are about 900µs and the header mark is about 6750µs so this will add up to 63,2 ms.

I used this formula: (63 \* 900 µs) + (6750 µs) = 63.45 ms.

I hope this is correct.

However my arduino has to update the display every time a displayvalue changes and this takes about 170ms which is way too long.

For the invulnerability problem while sending, the irlib uses an interupt which triggers the receiving code in the library and you can do the same for the trigger button (the arduino uno/nano has two interrupts). So your arduino should be able to receive a signal, send a signal and display something.

We didn't experience invulnerability, because we aren't ready to play with the Lightduino Guns, currently we are testing different lenses and voltages for the ir led as the homemade Lightstrike Guns are much more powerful and will hit the Lightstrike weapons just with the reflections of the ir light. Then we will need to build a calibration station. So that the laser pointer will point to the exact same spot as the ir led and the ir led should not be that powerful that the reflections of the ir light will trigger the hit sensor on the original weapons.

As you can thee in the Lightduino Sketch all weapon modes got a delay, so there is no burst mode. The fastet weapon mode is able to send a signal every 175ms (if you release the trigger in the meantime).

```
code,   type, enabled,     name,        damage, charges, bounceDelay, continuesDelay, reloadTime
0x0102,  'P',  true,   "Laserstrike",    -10,      12,      175,            250,        1750
```

**Comment by lhk** [comment]
Very interesting information, thanks
